# Generated by Django 5.0.2 on 2024-03-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_who_id_task_who'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='complete',
            field=models.CharField(default='Not Completed', max_length=200),
        ),
    ]
