# Generated by Django 5.0.2 on 2024-03-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_task_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='complete',
            field=models.CharField(default='Not Yet', max_length=200),
        ),
    ]
